### ISSUE TITLE
Repository and code maintenance

### ISSUE THREAD

**Issue by alexattws** [tws-inc/gitea-group-sync#9]
Hi,

Unfortunately, I don't see myself or my organization as having enough time and/or budget to devote to maintaining this project going forward. What do people think about creating a separate GitHub organization, transferring this repo over to it and giving current willing contributors membership to continue to maintain it?

@ykorzikowski, @thoscut, @localleon, @Ingomancer, would you guys be interested?

I'm open to any suggestions.

Thanks.

**Comment by localleon** [comment]
Greetings,

it is a shame to hear that you can no longer continue the project.

How many people are still actively using the project (Traffic Graph may give some insight into this)? If we only have a few users, maybe a single maintainer (instead of an organization) could be sufficient.

Has someone ever issued a feature request on the official Gitea-Project on syncing LDAP-Groups with Gitea-Groups? Maybe the Gitea-Project could be interested? In the long term it seems like Gitea will be one of the main self-hosted Git Applications, since Gitlab seems to be changing its strategy. This could be a growing opportunity for the project.

At our company we decided that the granular control over users permissions that ldap-group-sync provided us with, is not really needed in a small team (which Gitea is intended for). We just switched to the built-in permission system where a single maintainer is responsible for a repository and creates/assigns permissions. Organizations are not really needed in a small team, but that's just my opinion.

Kind Regards,
Leon

**Comment by alexattws** [comment]
The code will continue to work, unless Gitea API changes too much. I (and my colleague @selukov ) may still jump in and do some fixes for ourselves, but we just don't have enough time/budget to do anything too involved. For example, I've been really itching to thoroughly test the somewhat recent merged commits for months, but I just can't find the time. It would be great to get a couple more guys involved so this project doesn't die.

**Comment by alexattws** [comment]
Ok, I will go ahead and proceed with the plan.
